### ISSUE TITLE
Make report on unswered issues and try to respond

### ISSUE THREAD

**Issue by matentzn** [obophenotype/uberon#1987]
Using Github API maybe

**Comment by matentzn** [comment]
Hey @gouttegd I am assigning you here only since you are already working on API stuff. 

Basically it would be great to have a small script that generates a markdown table like:

| Issue | Person | Uberon team? | Assignee | 
| --- | ---- | ----- | ---- |
|  [Close all issues that have not seen activity in last 3 years](https://github.com/obophenotype/uberon/issues/1988) | @matentzn | Yes | @gouttegd |
|  [Close all issues that have not seen activity in last 3 years](https://github.com/obophenotype/uberon/issues/1988) | @matentzn | Yes | @gouttegd |
|  [eyestalk](https://github.com/obophenotype/uberon/issues/1938) | @ANiknejad | No | |

**Comment by gouttegd** [comment]
I have a first draft that does most of the job. It gives issues that were last updated more than 180 days ago (truncated here to the first 50 such issues).

For now, the author of an issue is considered to be part of the "Uberon team" if that user either is a member of the _Obophenotype_ organization (_member_) or has been invited to contribute to the repository (_contributor_). This is the easiest way to do it, but it’s not really suitable for Uberon given that several contributors are effectively considered part of the team even though they are not _formally_ members or contributors from GitHub’s point of view. I’ll add a check against an externally-maintained list of contributors later.

| Issue | Author | Uberon team? | Assignee(s) |
| ----- | ------ | ------------ | ----------- |
| [consistency in tooth terms](https://github.com/obophenotype/uberon/issues/1757) | [@megbalk](https://github.com/megbalk) | No |  |
| [UBERON:0006871 embryonic footplate - change synonym scope](https://github.com/obophenotype/uberon/issues/1728) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [EHDAA2:0001090 medulla oblongata alar plate (human), wrong part_of relationship](https://github.com/obophenotype/uberon/issues/1725) | [@ANiknejad](https://github.com/ANiknejad) | No |  |
| [Xrefs without prefixes in OBO export](https://github.com/obophenotype/uberon/issues/1724) | [@cthoyt](https://github.com/cthoyt) | No |  |
| [UBERON:4200132 tuber](https://github.com/obophenotype/uberon/issues/1704) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [UBERON:7500041 tip of digit](https://github.com/obophenotype/uberon/issues/1701) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [UBERON:4200179 manual claw](https://github.com/obophenotype/uberon/issues/1699) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [UBERON:0018306 bulge and UBERON:0010188 protuberance](https://github.com/obophenotype/uberon/issues/1698) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [Some "buccal" terms missing part_of parent](https://github.com/obophenotype/uberon/issues/1697) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [Typo in synonym of UBERON:0018133 monotreme bill](https://github.com/obophenotype/uberon/issues/1696) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [Typo in def of UBERON:0011933 vibrissa unit](https://github.com/obophenotype/uberon/issues/1695) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [Mapping external references](https://github.com/obophenotype/uberon/issues/1694) | [@computationdoc](https://github.com/computationdoc) | No |  |
| ["anatomical collection" in Uberon and "anatomical set" in FMA](https://github.com/obophenotype/uberon/issues/1693) | [@ChristianKleineidam](https://github.com/ChristianKleineidam) | No |  |
| [developing anatomical structure missing parent](https://github.com/obophenotype/uberon/issues/1691) | [@pgaudet](https://github.com/pgaudet) | No |  |
| [Add TC UBERON:0002542 'scale' never in Homo sapiens?](https://github.com/obophenotype/uberon/issues/1690) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [NTR: right gastric artery](https://github.com/obophenotype/uberon/issues/1687) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [NTRs: greater + lesser palatine foramen](https://github.com/obophenotype/uberon/issues/1686) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [NTR: Tenon capsule](https://github.com/obophenotype/uberon/issues/1685) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [anatomical projection and incorrect FMA link](https://github.com/obophenotype/uberon/issues/1684) | [@ChristianKleineidam](https://github.com/ChristianKleineidam) | No |  |
| [NTR: periosteum of orbit](https://github.com/obophenotype/uberon/issues/1683) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [NTR: epitrochlear lymph node](https://github.com/obophenotype/uberon/issues/1679) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [Missing textual definitions](https://github.com/obophenotype/uberon/issues/1678) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [Some definitions don't start with uppercase and don't end with a period](https://github.com/obophenotype/uberon/issues/1677) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [NTR: ganglion impar](https://github.com/obophenotype/uberon/issues/1675) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [NTR: glomus coccygeum](https://github.com/obophenotype/uberon/issues/1674) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [Typo in label of UBERON:0008989 submocosal esophageal gland](https://github.com/obophenotype/uberon/issues/1673) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [Typo in definition of several "epithelium" terms ](https://github.com/obophenotype/uberon/issues/1669) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [Def of UBERON:0000444 'lymphoid follicle' contains "." only](https://github.com/obophenotype/uberon/issues/1668) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [Incorrect UMLS Xref for UBERON:0004016](https://github.com/obophenotype/uberon/issues/1663) | [@pecan88](https://github.com/pecan88) | No |  |
| [Lack of consistency in use of kidney vs. renal in preferred terms [Typo/Bug]](https://github.com/obophenotype/uberon/issues/1654) | [@rich-brennan](https://github.com/rich-brennan) | No |  |
| [Experiment: materialize phylo-specific uberon classes](https://github.com/obophenotype/uberon/issues/1645) | [@cmungall](https://github.com/cmungall) | Yes |  |
| [standardize on creation date property](https://github.com/obophenotype/uberon/issues/1644) | [@cmungall](https://github.com/cmungall) | Yes |  |
| [Incorporate ICDOT mappings](https://github.com/obophenotype/uberon/issues/1642) | [@cmungall](https://github.com/cmungall) | Yes |  |
| [parent of 'life cycle stage' unclear](https://github.com/obophenotype/uberon/issues/1640) | [@johnwjudkins](https://github.com/johnwjudkins) | No |  |
| [human-view.owl should remove contextual axioms in final release](https://github.com/obophenotype/uberon/issues/1635) | [@dosumis](https://github.com/dosumis) | Yes | [@cmungall](https://github.com/cmungall) |
| [Bad URI for image depiction](https://github.com/obophenotype/uberon/issues/1634) | [@balhoff](https://github.com/balhoff) | Yes |  |
| [Request for comments: model anatomical spaces as material entities, consistent with GO](https://github.com/obophenotype/uberon/issues/1633) | [@cmungall](https://github.com/cmungall) | Yes |  |
| [UBERON:0018241 prime adult stage](https://github.com/obophenotype/uberon/issues/1632) | [@ANiknejad](https://github.com/ANiknejad) | No | [@nicolevasilevsky](https://github.com/nicolevasilevsky) |
| [Adding a whole bunch of species-specific terms](https://github.com/obophenotype/uberon/issues/1631) | [@stevevanhooser](https://github.com/stevevanhooser) | No |  |
| [NTR: endodontium](https://github.com/obophenotype/uberon/issues/1623) | [@paola-scibite](https://github.com/paola-scibite) | No |  |
| [uberon uses a 'contains process' relation that has a non-existing IRI](https://github.com/obophenotype/uberon/issues/1616) | [@cmungall](https://github.com/cmungall) | Yes |  |
| [Invalid Xrefs in human-view.obo](https://github.com/obophenotype/uberon/issues/1615) | [@rpwagner](https://github.com/rpwagner) | No |  |
| [Why doesn't adventitia subclass connective tissue?](https://github.com/obophenotype/uberon/issues/1611) | [@ChristianKleineidam](https://github.com/ChristianKleineidam) | No |  |
| [Ligament and Ligament organ](https://github.com/obophenotype/uberon/issues/1610) | [@ChristianKleineidam](https://github.com/ChristianKleineidam) | No |  |
| [nested logical definitions](https://github.com/obophenotype/uberon/issues/1609) | [@ramonawalls](https://github.com/ramonawalls) | No |  |
| [import BSPO terms](https://github.com/obophenotype/uberon/issues/1608) | [@ramonawalls](https://github.com/ramonawalls) | No |  |
| [NTR: oral fluid](https://github.com/obophenotype/uberon/issues/1603) | [@cmrn-rhi](https://github.com/cmrn-rhi) | No |  |
| [lacrimal apparatus function?](https://github.com/obophenotype/uberon/issues/1602) | [@drseb](https://github.com/drseb) | Yes |  |
| [Add perioral region?](https://github.com/obophenotype/uberon/issues/1599) | [@drseb](https://github.com/drseb) | Yes |  |
| [Make part relationship for tracheobronchial epithelium to tracheobronchial tree](https://github.com/obophenotype/uberon/issues/1595) | [@mkeays](https://github.com/mkeays) | Yes |  |

**Comment by gouttegd** [comment]
I have a first draft that does most of the job. It gives issues that were last updated more than 180 days ago (truncated here to the first 50 such issues).

For now, the author of an issue is considered to be part of the "Uberon team" if that user either is a member of the Obophenotype organization (member) or has been invited to contribute to the repository (contributor). This is the easiest way to do it, but it’s not really suitable for Uberon given that several contributors are effectively considered part of the team even though they are not formally members or contributors from GitHub’s point of view. I’ll add a check against an externally-maintained list of contributors later.


| Issue | Author | Uberon team? | Assignee(s) |
| ----- | ------ | ------------ | ----------- |
| [consistency in tooth terms](https://github.com/obophenotype/uberon/issues/1757) | @[megbalk](https://github.com/megbalk) | No |  |
| [UBERON:0006871 embryonic footplate - change synonym scope](https://github.com/obophenotype/uberon/issues/1728) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [EHDAA2:0001090 medulla oblongata alar plate (human), wrong part_of relationship](https://github.com/obophenotype/uberon/issues/1725) | @[ANiknejad](https://github.com/ANiknejad) | No |  |
| [Xrefs without prefixes in OBO export](https://github.com/obophenotype/uberon/issues/1724) | @[cthoyt](https://github.com/cthoyt) | No |  |
| [UBERON:4200132 tuber](https://github.com/obophenotype/uberon/issues/1704) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [UBERON:7500041 tip of digit](https://github.com/obophenotype/uberon/issues/1701) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [UBERON:4200179 manual claw](https://github.com/obophenotype/uberon/issues/1699) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [UBERON:0018306 bulge and UBERON:0010188 protuberance](https://github.com/obophenotype/uberon/issues/1698) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [Some "buccal" terms missing part_of parent](https://github.com/obophenotype/uberon/issues/1697) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [Typo in synonym of UBERON:0018133 monotreme bill](https://github.com/obophenotype/uberon/issues/1696) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [Typo in def of UBERON:0011933 vibrissa unit](https://github.com/obophenotype/uberon/issues/1695) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [Mapping external references](https://github.com/obophenotype/uberon/issues/1694) | @[computationdoc](https://github.com/computationdoc) | No |  |
| ["anatomical collection" in Uberon and "anatomical set" in FMA](https://github.com/obophenotype/uberon/issues/1693) | @[ChristianKleineidam](https://github.com/ChristianKleineidam) | No |  |
| [developing anatomical structure missing parent](https://github.com/obophenotype/uberon/issues/1691) | @[pgaudet](https://github.com/pgaudet) | No |  |
| [Add TC UBERON:0002542 'scale' never in Homo sapiens?](https://github.com/obophenotype/uberon/issues/1690) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [NTR: right gastric artery](https://github.com/obophenotype/uberon/issues/1687) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [NTRs: greater + lesser palatine foramen](https://github.com/obophenotype/uberon/issues/1686) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [NTR: Tenon capsule](https://github.com/obophenotype/uberon/issues/1685) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [anatomical projection and incorrect FMA link](https://github.com/obophenotype/uberon/issues/1684) | @[ChristianKleineidam](https://github.com/ChristianKleineidam) | No |  |
| [NTR: periosteum of orbit](https://github.com/obophenotype/uberon/issues/1683) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [NTR: epitrochlear lymph node](https://github.com/obophenotype/uberon/issues/1679) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [Missing textual definitions](https://github.com/obophenotype/uberon/issues/1678) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [Some definitions don't start with uppercase and don't end with a period](https://github.com/obophenotype/uberon/issues/1677) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [NTR: ganglion impar](https://github.com/obophenotype/uberon/issues/1675) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [NTR: glomus coccygeum](https://github.com/obophenotype/uberon/issues/1674) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [Typo in label of UBERON:0008989 submocosal esophageal gland](https://github.com/obophenotype/uberon/issues/1673) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [Typo in definition of several "epithelium" terms ](https://github.com/obophenotype/uberon/issues/1669) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [Def of UBERON:0000444 'lymphoid follicle' contains "." only](https://github.com/obophenotype/uberon/issues/1668) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [Incorrect UMLS Xref for UBERON:0004016](https://github.com/obophenotype/uberon/issues/1663) | @[pecan88](https://github.com/pecan88) | No |  |
| [Lack of consistency in use of kidney vs. renal in preferred terms [Typo/Bug]](https://github.com/obophenotype/uberon/issues/1654) | @[rich-brennan](https://github.com/rich-brennan) | No |  |
| [Experiment: materialize phylo-specific uberon classes](https://github.com/obophenotype/uberon/issues/1645) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [standardize on creation date property](https://github.com/obophenotype/uberon/issues/1644) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [Incorporate ICDOT mappings](https://github.com/obophenotype/uberon/issues/1642) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [parent of 'life cycle stage' unclear](https://github.com/obophenotype/uberon/issues/1640) | @[johnwjudkins](https://github.com/johnwjudkins) | No |  |
| [human-view.owl should remove contextual axioms in final release](https://github.com/obophenotype/uberon/issues/1635) | @[dosumis](https://github.com/dosumis) | Yes | @[cmungall](https://github.com/cmungall) |
| [Bad URI for image depiction](https://github.com/obophenotype/uberon/issues/1634) | @[balhoff](https://github.com/balhoff) | Yes |  |
| [Request for comments: model anatomical spaces as material entities, consistent with GO](https://github.com/obophenotype/uberon/issues/1633) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [UBERON:0018241 prime adult stage](https://github.com/obophenotype/uberon/issues/1632) | @[ANiknejad](https://github.com/ANiknejad) | No | @[nicolevasilevsky](https://github.com/nicolevasilevsky) |
| [Adding a whole bunch of species-specific terms](https://github.com/obophenotype/uberon/issues/1631) | @[stevevanhooser](https://github.com/stevevanhooser) | No |  |
| [NTR: endodontium](https://github.com/obophenotype/uberon/issues/1623) | @[paola-scibite](https://github.com/paola-scibite) | No |  |
| [uberon uses a 'contains process' relation that has a non-existing IRI](https://github.com/obophenotype/uberon/issues/1616) | @[cmungall](https://github.com/cmungall) | Yes |  |
| [Invalid Xrefs in human-view.obo](https://github.com/obophenotype/uberon/issues/1615) | @[rpwagner](https://github.com/rpwagner) | No |  |
| [Why doesn't adventitia subclass connective tissue?](https://github.com/obophenotype/uberon/issues/1611) | @[ChristianKleineidam](https://github.com/ChristianKleineidam) | No |  |
| [Ligament and Ligament organ](https://github.com/obophenotype/uberon/issues/1610) | @[ChristianKleineidam](https://github.com/ChristianKleineidam) | No |  |
| [nested logical definitions](https://github.com/obophenotype/uberon/issues/1609) | @[ramonawalls](https://github.com/ramonawalls) | No |  |
| [import BSPO terms](https://github.com/obophenotype/uberon/issues/1608) | @[ramonawalls](https://github.com/ramonawalls) | No |  |
| [NTR: oral fluid](https://github.com/obophenotype/uberon/issues/1603) | @[cmrn-rhi](https://github.com/cmrn-rhi) | No |  |
| [lacrimal apparatus function?](https://github.com/obophenotype/uberon/issues/1602) | @[drseb](https://github.com/drseb) | Yes |  |
| [Add perioral region?](https://github.com/obophenotype/uberon/issues/1599) | @[drseb](https://github.com/drseb) | Yes |  |
| [Make part relationship for tracheobronchial epithelium to tracheobronchial tree](https://github.com/obophenotype/uberon/issues/1595) | @[mkeays](https://github.com/mkeays) | Yes |  |

**Comment by matentzn** [comment]
No, I think you are doing the right thing - this is perfect. Let's make this all a bit more organised:

All people that are part of the wider Uberon team should be in
https://github.com/orgs/obophenotype/teams/uberon-curators

I have sent out some invites. Check only that team - if you are listed in there (and only then), you are considered core team. I will update the list when I see the names coming in - maybe you can send me a list of all github handles you see outside that list and I can update.

**Comment by paolaroncaglia** [comment]
Hi @gouttegd and @matentzn ,
I have followed up on all tickets above opened by my alter ego paola-scibite. She won't join obophenotype for now ;-) (notifications go to yet another email account, I'd rather keep everything in one place...). Thanks for your work on this!

**Comment by gouttegd** [comment]
@matentzn The script will be available in [this repo](https://github.com/gouttegd/grainyhead).

It's in a very rough shape for now, but it already works (for some definition of "works", anyway: for example there's absolutely no error checking of any kind) for what you want to do.

If you want to try it to get the list you want:
1. Create an [access token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token).
2. Create a configuration file named `~/Library/Application Support/grainyhead/config` with the following:

```
[default]
user: obophenotype
repo: oberon
token: <your access token>
```

3. From the cloned repo:

```
$ PYTHONPATH=. python fbcam/grainyhead/main.py issues --older-than 180 --team obophenotype/uberon-cl-curators > old-issues.md
```

Alternatively you can already install the package in your per-user Python environment (which would then install the `grh` command in your PATH), but I'd say it's probably a bit premature for now.

Warning: I make no promise that I will not change the format of the configuration file or the syntax of the command line.

**Comment by matentzn** [comment]
This is amazing! Will come back to this next week - now I am on vacation ;) supper cooool.

**Comment by matentzn** [comment]
Awesome thank you @gouttegd; Currently I get:

```
matentzn@mbp.local:~/ws/grainyhead (master) $ cat ~/Library/Application\ Support/grainyhead/config 
[default]
user: obophenotype
repo: uberon
token: IHAVEADDEDMYTOKENHERE
matentzn@mbp.local:~/ws/grainyhead (master) $ PYTHONPATH=. python fbcam/grainyhead/main.py issues --older-than 180 --team obophenotype/uberon-cl-curators > old-issues.md
Traceback (most recent call last):
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'repository'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fbcam/grainyhead/main.py", line 250, in <module>
    grh()
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click_shell/core.py", line 164, in invoke
    ret = super(Shell, self).invoke(ctx)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "fbcam/grainyhead/main.py", line 133, in list_issues
    repo = grh.repository
  File "fbcam/grainyhead/main.py", line 82, in repository
    repo_url = self._config.get(self._name, 'repository')
  File "/Users/matentzn/opt/anaconda3/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'repository' in section: 'default'
matentzn@mbp.local:~/ws/grainyhead (master) $ 
```

**Comment by gouttegd** [comment]
Told you I don't promise the interface wouldn't change. :D The comment above is already obsolete, this weekend I replace the `user` and `repo` options with a single `repository` option, for simplicity's sake.

The config file should now be like:

```
[default]
repository: obophenotype/uberon
token: <your access token>
```

**Comment by matentzn** [comment]
Update to command:

```
PYTHONPATH=. python fbcam/grainyhead/main.py issues --older-than 180 --team uberon-cl-curators > old-issues.md
```

I will close this issue now, as its all done! Thank you @gouttegd
