### ISSUE TITLE
PR import broken

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2249]
Can't seem to get PR import to work in UBERON.
Did manage to RO import to work though so it seems specific to PR
could use some help, thanks :) 

```
2022-01-25 08:56:43,476 ERROR (CommandRunner:4310) Could not find specified ontology http://purl.obolibrary.org/obo/pr.owl for --source
Exception in thread "main" java.lang.NullPointerException
	at uk.ac.manchester.cs.owlapi.modularity.SyntacticLocalityModuleExtractor.asAxiomSet(SyntacticLocalityModuleExtractor.java:287)
	at uk.ac.manchester.cs.owlapi.modularity.SyntacticLocalityModuleExtractor.<init>(SyntacticLocalityModuleExtractor.java:282)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4357)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
make: *** [uberon.Makefile:416: imports/pr_import.owl] Error 1
```

**Comment by matentzn** [comment]
@shawntanzk do you want to change PR import in Uberon to the PRO slim? This will make the process much slimmer as well.

Steps:

- [ ] change uberon-odk.yaml to refer to the slim (see PCL, CL)
- [ ] open src/ontology/imports/pr_terms_combined.txt (or src/ontology/tmp/seed.txt) and copy all PR references in there and add them to the PRO slim like you did last time (make sure no duplicates, use `cat seed.txt | sort | uniq > new_seed.txt` to get a unique list).
- [ ] Make sure that in `uberon.Makefile`, the default `import/pr_import.owl` is used, i.e. comment out the one made by uberon.Makefile. 
- [ ] Have me review the PR

**Comment by shawntanzk** [comment]
will do :)

**Comment by shawntanzk** [comment]
@matentzn 
Currently commenting out PRO stuff in uberon.makefile (assume that the same has to be done with mirror/pr.owl stuff too) and notice that mirror/aminoacid.owl will be affected - do you know what I should do with it? Thanks
