### ISSUE TITLE
Release failing at life-stages-composite.owl

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/uberon#2555]
Error: 
```
% tail -30 subsets/life-stages-composite.owl.LOG
2022-06-29 04:43:07,408 WARN  (OWLGraphWrapperExtended:936) Unable to retrieve the value of oboInOwl#id as the identifier for http://www.w3.org/2002/07/owl#Thing; we will use an original iri as the identifier.
2022-06-29 04:43:07,409 WARN  (OWLGraphWrapperExtended:936) Unable to retrieve the value of oboInOwl#id as the identifier for http://www.w3.org/2002/07/owl#Thing; we will use an original iri as the identifier.
A:Thing Thing
2022-06-29 04:43:08,874 ERROR (CommandRunner:4815) could not parse:--no-check
org.semanticweb.owlapi.io.OWLOntologyCreationIOException: /work/src/ontology/--no-check (No such file or directory)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:230)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1254)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1208)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1108)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1064)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:163)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:150)
	at owltools.io.ParserWrapper.parse(ParserWrapper.java:132)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4803)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
Caused by: java.io.FileNotFoundException: /work/src/ontology/--no-check (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStreamFromContentEncoding(AbstractOWLParser.java:179)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:141)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:264)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:72)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:220)
	... 11 more
```

**Comment by matentzn** [comment]
You can try again now @shawntanzk
